version: "3.8"

services:

  redis:
    image: redis:7-alpine
    container_name: cloudscope_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudscope_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379   # Override URL agar mengarah ke service Redis
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - /tmp/cloudscope:/tmp/cloudscope  # Shared temp dir antara api dan worker
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudscope_worker
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - /tmp/cloudscope:/tmp/cloudscope  # Shared temp dir
    command: celery -A app.celery_config.celery worker --loglevel=info

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudscope_flower
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - worker
    command: celery -A app.celery_config.celery flower --port=5555