server {
    listen 80;
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/certs/cloudscope.crt;
    ssl_certificate_key /etc/nginx/certs/cloudscope.key;

    location / {
        proxy_pass http://cloudscope-react:3000;
    }

    location /api/ {
        proxy_pass http://cloudscope-fastapi:8000;
    }
}
